{{- if .Values.backend.enabled -}}
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ include "gpt-sample-app.fullname" . }}
  labels:
    {{- include "gpt-sample-app.labels" . | nindent 4 }}
spec:
  template:
    spec:
      {{- with .Values.backend.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          env:
            - name: "MILVUS_HOST"
              value: {{ .Values.milvus.host }}
            - name: "MILVUS_PORT"
              value: {{ .Values.milvus.port }}
            - name: "MILVUS_COLLECTION"
              value: {{ .Values.milvus.collection }}
            - name: "INFERENCE_ENDPOINT"
              value: {{ .Values.inference.endpoint }}
            - name: "SSL_VERIFY"
              value: {{ .Values.s3.sslVerify }}
            - name: "S3_REGION"
              value: {{ .Values.s3.region }}
            - name: "ACCESS_KEY"
              value: {{ .Values.s3.accessKey }}
            - name: "SECRET_KEY"
              value: {{ .Values.s3.secretKey }}
            - name: "S3_ENDPOINT_URL"
              value: {{ .Values.s3.endpoint }}
            - name: "BUCKET_NAME"
              value: {{ .Values.s3.bucket }}
          {{- range .Values.backend.env }}
            - name: {{ .name | quote }}
              value: {{ .value | quote }}
          {{- end }}
{{- end }}